notifications:
  email: false
git:
  quiet: true
  depth: false
jdk: openjdk11
os: linux
addons:
  apt:
    packages:
      - curl
      - sudo
      - lsof
      - docker-ce
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 8000 8080
  #
  - python -m pip install --upgrade httpie docker-compose
language: python
python: 3.8
jobs:
  include:
    - stage: test
      name: test
      before_script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw
        - java -jar $TRAVIS_BUILD_DIR/gateway/target/*.jar &
        - java -jar $TRAVIS_BUILD_DIR/spring-cloud-functions/target/*.jar &
        - wait_for 8000 8080
      script:
        - http :8080/api/function name=java far=jar
      after_script: stop_any 80 8000 8080
    - stage: test
      name: docker
      before_script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw
        - cd $TRAVIS_BUILD_DIR && docker-compose down -v --rmi local
        - cd $TRAVIS_BUILD_DIR && docker-compose pull --ignore-pull-failures
        - cd $TRAVIS_BUILD_DIR && docker-compose up --build -d
        - cd $TRAVIS_BUILD_DIR && docker-compose logs -f -t &
        - wait_for 80
        - sleep 15s
      script:
        - http :/api/function name=docker kind=docker-compose
      after_script: cd $TRAVIS_BUILD_DIR && docker-compose down -v --rmi local
cache:
  pip: true
  packages: true
  directories:
    - ~/.docker
    - ~/.m2
